#!/usr/bin/env python3
#Author: Tirth Jayswal
#Seneca Id= tcjayswal (153799200)
#Date Created = 2022/10/17

import sys

int('The first variable is ' + sys.argv[1])
print('The second variable is ' + sys.argv[2])
print('The name of the script is ' + sys.argv[0])
print(sys.argv[0] + ', ' + sys.argv[1] +  ', ' + sys.argv[2])

def helloWorld():
	print(‘Hello World’)


helloWorld()

