#!/usr/bin/env python3
#Author: Tirth Jayswal
#Seneca Id= tcjayswal (153799200)
#Date Created = 2022/10/17

file = open('C:/Users/Tirth Jayswal/Downloads/tirth.txt','w+')
print('The required file has been created in your Downloads folder. ')
